### ISSUE TITLE
[Feature Request]: Modify code in quickfix, write it to file

### ISSUE THREAD

**Issue by lmburns** [arsham/listish.nvim#2]
I don't know if it would be possible to add something that is similar to the functionality of [`stefandtw/quickfix-reflector.vim`](https://github.com/stefandtw/quickfix-reflector.vim). Where a command like `:vimgrep` could populate the quickfix list, and then a `%s/<search>/<replace>` command could be ran on the quickfix list, causing each change to be written to the corresponding file.

This would need to involve checking whether or not the item in the quickfix list is a note or an actual line in a file.

Just as a note, an issue I had with the plugin mentioned above is that it does not always work very well with [`nvim-bqf`](https://github.com/kevinhwang91/nvim-bqf). The preview window from `bqf` will not always close, and your plugin seems to work wonderfully with `bqf`.

**Comment by arsham** [comment]
> I don't know if it would be possible to add something that is similar to the functionality of [`stefandtw/quickfix-reflector.vim`](https://github.com/stefandtw/quickfix-reflector.vim). Where a command like `:vimgrep` could populate the quickfix list, and then a `%s/<search>/<replace>` command could be ran on the quickfix list, causing each change to be written to the corresponding file.

I never thought about doing this. I usually use `cdo` for these types of operation. But I can look into that option.

> This would need to involve checking whether or not the item in the quickfix list is a note or an actual line in a file.

Good point! It is totally doable.
 
> Just as a note, an issue I had with the plugin mentioned above is that it does not always work very well with [`nvim-bqf`](https://github.com/kevinhwang91/nvim-bqf). The preview window from `bqf` will not always close, and your plugin seems to work wonderfully with `bqf`.

Thanks! I'm a big fan of the `nvim-bqf` plugin. Glad to hear your are using these two together.

**Comment by arsham** [comment]
Having looked at the code of the plugin, I understand it sets the `modifiable` flag on the local/qf lists. I'm not comfortable doing this because it will cause any autocmds to react to changes on the buffer.

I can think of two feasible solution:

1. Leave it as is. A `cdo` with substitution would work as expected. However it would error out if the term is not on the line due to the `Notes` or manual addition of lines with `<leader>qq`, `<leader>ww`, etc.
2. Provide a command to clean up the list, removing any notes created by this plugin. This will let user use the `cdo` command without any errors.

What do you reckon?

**Comment by lmburns** [comment]
I've never used `cdo`, but I am going to start. For whatever it is worth, another plugin that makes the quickfix list modifiable is [`replacer.nvim`](https://github.com/gabrielpoca/replacer.nvim). 

I think the second option wouldn't be bad. Add a command that would be able to filter out quickfix items that do not correspond to lines in a file. So then it would be easier when using `cdo` or whatever other command to modify the buffer.

Since I wasn't aware of the `cdo` command, I don't think that making the buffer modifiable is that important. The only reason I could ever see use for that would be to go through and modify each line individually.

Something else that could possibly be done is to create a command that is similar to `cdo` but allow for something like `quickfix-reflector.vim`'s `qf_join_changes`, where all changes could be undone with a single `undo` command

**Comment by lmburns** [comment]
Something else I might add, just as a suggestion. For your library you have `arshlib.nvim`, perhaps the UI part of it could somehow be integrated with [`dressing.nvim`](https://github.com/stevearc/dressing.nvim). All it would need to do is call `vim.ui.input`, and then the user could choose between `telescope`, `fzf`, `fzf-lua`, `nui`, or the `builtin`, and wouldn't necessarily have to have `nui` as a dependency for the library.

I'm not sure if this would work, I'm trying it out now. I'm not sure if `vim.ui.select`/`vim.ui.input` are as featureful as `nui`. So maybe disregard this. I'm still going to mess around a little and see if I can figure anything out.

**Comment by arsham** [comment]
The `cdo`, `ldo`, `cfdo` and `lfdo` commands are awesome, give them a try. You can also run the `update` and `undo` on them which is handy.

Just a note: the note you create actually have the necessary information on the file and the line. Therefore any operation you do with `cdo`/`ldo`, `cfdo`/`lfdo` commands will still work.

Regarding the `ui`, I totally agree with you. It's worth creating a new issue because it is unrelated to this conversation.

Thanks for all the ideas, I appreciate it.

**Comment by lmburns** [comment]
I'd say that this could be closed now that there have been commits referencing this and that `cdo` and such will act on lines actually referencing spots in files. And making the quickfix list modifiable doesn't seem to be wanted or necessary.

**Comment by arsham** [comment]
Thanks mate. If you have any other suggestions please feel free to make an issue.

I have a few other tiny plugins that might interest you.

Thank you for your support!
